# PRIMENEST RETAIL

In [ ]:
# Retail Sales & Inventory Analysis

## Python Data Analysis Project

### Project Overview

This project analyzes retail sales, customer, product, order, payment, 
employee, category, and inventory data using Python.

The analysis focuses on data preparation, exploratory data analysis,
statistical analysis, visualization, and the generation of
business insights and recommendations.

### Tools Used

- Python
- Pandas
- NumPy
- Matplotlib
- Jupyter Notebook
- PostgreSQL

# IMPORTING LIBRARIES & DRIVER

# - Python | Pandas Library

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [7]:
print("Libraries imported successfully!")

Libraries imported successfully!

# - SQLAlchemy Library

In [8]:
import sqlalchemy
print(sqlalchemy.__version__)

2.0.43

In [9]:
from sqlalchemy import create_engine

# - PostgreSQL Driver (The translator/connector)

In [2]:
%pip install psycopg2-binary

Requirement already satisfied: psycopg2-binary in c:\users\user\anaconda3\lib\site-packages (2.9.12)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import psycopg2
print(psycopg2.__version__)

2.9.12 (dt dec pq3 ext lo64)

# CONNECTING PYTHON TO POSTGRESQL

In [2]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:3640@localhost:5432/ecommerce_db"
)

In [3]:
with engine.connect() as connection:
    print("Connected to PrimeNest Retail database successfully!")

Connected to PrimeNest Retail database successfully!

# LOADING TABLES INTO PANDAS

# - Test Running Using Customer Table

In [8]:
customers = pd.read_sql("SELECT * FROM customers", engine)

customers.head()

,customer_id,first_name,last_name,gender,email,phone,address,city,registration_date
0,1101,Chinedu,Okafor,Male,chinedu.okafor@email.com,08030000001,15 Admiralty Way,Lagos,2026-08-08
1,1102,Ada,Eze,Female,ada.eze@email.com,08030000002,12 GRA,Port Harcourt,2026-08-08
2,1103,Emeka,Nwosu,Male,emeka.nwosu@email.com,08030000003,45 Independence Layout,Enugu,2026-08-08
3,1104,Ngozi,Umeh,Female,ngozi.umeh@email.com,08030000004,23 Wuse Zone 4,Abuja,2026-08-08
4,1105,Tunde,Adebayo,Male,tunde.adebayo@email.com,08030000005,8 Bodija,Ibadan,2026-08-08

In [9]:
customers.shape

(20, 9)

# - Loading the Rest of PrimeNest Retail Tables

In [10]:
employees = pd.read_sql("SELECT * FROM employees_", engine)
products = pd.read_sql("SELECT * FROM products", engine)
categories = pd.read_sql("SELECT * FROM categories", engine)
suppliers = pd.read_sql("SELECT * FROM suppliers", engine)
inventory = pd.read_sql("SELECT * FROM inventory", engine)
orders = pd.read_sql("SELECT * FROM orders", engine)
order_details = pd.read_sql("SELECT * FROM order_details", engine)
payments = pd.read_sql("SELECT * FROM payments", engine)

# - Confirming Tables Load

In [11]:
print("Customers:", customers.shape)
print("Employees:", employees.shape)
print("Products:", products.shape)
print("Categories:", categories.shape)
print("Suppliers:", suppliers.shape)
print("Inventory:", inventory.shape)
print("Orders:", orders.shape)
print("Order Details:", order_details.shape)
print("Payments:", payments.shape)

Customers: (20, 9)
Employees: (10, 7)
Products: (20, 8)
Categories: (10, 3)
Suppliers: (10, 6)
Inventory: (20, 5)
Orders: (100, 5)
Order Details: (200, 6)
Payments: (100, 6)

# UNDERSTANDING THE DATA

Before any analysis is made, it is important to inspect the structure and quality of each DataFrame.

# - Inspecting Customers (Test Run)

In [12]:
customers.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        20 non-null     int64
 1   first_name         20 non-null     object
 2   last_name          20 non-null     object
 3   gender             20 non-null     object
 4   email              20 non-null     object
 5   phone              20 non-null     object
 6   address            20 non-null     object
 7   city               20 non-null     object
 8   registration_date  20 non-null     object
dtypes: int64(1), object(8)
memory usage: 1.5+ KB

In [13]:
customers.head()

,customer_id,first_name,last_name,gender,email,phone,address,city,registration_date
0,1101,Chinedu,Okafor,Male,chinedu.okafor@email.com,08030000001,15 Admiralty Way,Lagos,2026-08-08
1,1102,Ada,Eze,Female,ada.eze@email.com,08030000002,12 GRA,Port Harcourt,2026-08-08
2,1103,Emeka,Nwosu,Male,emeka.nwosu@email.com,08030000003,45 Independence Layout,Enugu,2026-08-08
3,1104,Ngozi,Umeh,Female,ngozi.umeh@email.com,08030000004,23 Wuse Zone 4,Abuja,2026-08-08
4,1105,Tunde,Adebayo,Male,tunde.adebayo@email.com,08030000005,8 Bodija,Ibadan,2026-08-08

In [14]:
customers.describe(include='all')

,customer_id,first_name,last_name,gender,email,phone,address,city,registration_date
count,20.00000,20,20,20,20,20,20,20,20
unique,NaN,20,20,2,20,20,20,11,1
top,NaN,Chinedu,Okafor,Male,chinedu.okafor@email.com,08030000001,15 Admiralty Way,Lagos,2026-08-08
freq,NaN,1,1,10,1,1,1,4,20
mean,1110.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
std,5.91608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
min,1101.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25%,1105.75000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50%,1110.50000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75%,1115.25000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
max,1120.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# -  Inspecting Other Tables

In [15]:
#Using Python loop, rather than writing the same three commands eight times.

tables = {
    "Customers": customers,
    "Employees": employees,
    "Products": products,
    "Categories": categories,
    "Suppliers": suppliers,
    "Inventory": inventory,
    "Orders": orders,
    "Order Details": order_details,
    "Payments": payments
}

for name, df in tables.items():
    print(f"\n{'='*50}")
    print(name)
    print(f"{'='*50}")
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))

==================================================
Customers
==================================================
Shape: (20, 9)
Columns: ['customer_id', 'first_name', 'last_name', 'gender', 'email', 'phone', 'address', 'city', 'registration_date']

==================================================
Employees
==================================================
Shape: (10, 7)
Columns: ['employee_id', 'first_name', 'last_name', 'job_title', 'hire_date', 'salary', 'email']

==================================================
Products
==================================================
Shape: (20, 8)
Columns: ['product_id', 'product_name', 'category_id', 'supplier_id', 'unit_price', 'units_in_stock', 'reorder_level', 'discontinued']

==================================================
Categories
==================================================
Shape: (10, 3)
Columns: ['category_id', 'category_name', 'description']

==================================================
Suppliers
==================================================
Shape: (10, 6)
Columns: ['supplier_id', 'company_name', 'contact_name', 'phone', 'email', 'address']

==================================================
Inventory
==================================================
Shape: (20, 5)
Columns: ['inventory_id', 'product_id', 'quantity_available', 'warehouse_location', 'last_updated']

==================================================
Orders
==================================================
Shape: (100, 5)
Columns: ['order_id', 'customer_id', 'employee_id', 'order_date', 'order_status']

==================================================
Order Details
==================================================
Shape: (200, 6)
Columns: ['order_detail_id', 'order_id', 'product_id', 'quantity', 'unit_price', 'discount']

==================================================
Payments
==================================================
Shape: (100, 6)
Columns: ['payment_id', 'order_id', 'payment_date', 'payment_method', 'amount', 'payment_status']

# - DATA QUALITY ASSESSMENT

In [ ]:
"""
This is important to establish whether the data is complete, consistent, correctly formatted, and free from obvious duplication.

We'll check four things:

- Missing values
- Duplicate records
- Data types
- Basic inconsistencies

# - Check for Missing Values

In [ ]:
#Checking to see if any of our tables contain empty/null values.

In [16]:
for name, df in tables.items():
    print(f"\n{name}")
    print(df.isnull().sum())

Customers
customer_id          0
first_name           0
last_name            0
gender               0
email                0
phone                0
address              0
city                 0
registration_date    0
dtype: int64

Employees
employee_id    0
first_name     0
last_name      0
job_title      0
hire_date      0
salary         0
email          0
dtype: int64

Products
product_id        0
product_name      0
category_id       0
supplier_id       0
unit_price        0
units_in_stock    0
reorder_level     0
discontinued      0
dtype: int64

Categories
category_id      0
category_name    0
description      0
dtype: int64

Suppliers
supplier_id     0
company_name    0
contact_name    0
phone           0
email           0
address         0
dtype: int64

Inventory
inventory_id          0
product_id            0
quantity_available    0
warehouse_location    0
last_updated          0
dtype: int64

Orders
order_id        0
customer_id     0
employee_id     0
order_date      0
order_status    0
dtype: int64

Order Details
order_detail_id    0
order_id           0
product_id         0
quantity           0
unit_price         0
discount           0
dtype: int64

Payments
payment_id        0
order_id          0
payment_date      0
payment_method    0
amount            0
payment_status    0
dtype: int64

In [ ]:
"""
Observation: The missing-value assessment shows that all columns across the nine PrimeNest Retail tables contain zero missing values. This indicates 
that the dataset is complete and does not require missing-value treatment such as deletion or imputation. The absence of missing values also improves 
the reliability of subsequent calculations, aggregations and visualizations because the analysis will not be affected by incomplete records.

# - Check for Duplicate Records

In [ ]:
#Checking whether any entire rows have been duplicated.

In [18]:
for name, df in tables.items():
    print(f"{name}: {df.duplicated().sum()} duplicate rows")

Customers: 0 duplicate rows
Employees: 0 duplicate rows
Products: 0 duplicate rows
Categories: 0 duplicate rows
Suppliers: 0 duplicate rows
Inventory: 0 duplicate rows
Orders: 0 duplicate rows
Order Details: 0 duplicate rows
Payments: 0 duplicate rows

In [ ]:
"""
Observation: The duplicate-record assessment shows zero duplicate rows across all nine PrimeNest Retail tables. This indicates that each row represents 
a distinct record within its respective table and that there is no evidence of accidental row-level duplication. The absence of duplicates reduces the 
risk of inflated counts, sales figures, order volumes or other analytical measures and provides a reliable foundation for further analysis.

# - Check Data Types

In [ ]:
#Checking to see if Python interpreted each column correctly.

In [19]:
for name, df in tables.items():
    print(f"\n{name}")
    print(df.dtypes)

Customers
customer_id           int64
first_name           object
last_name            object
gender               object
email                object
phone                object
address              object
city                 object
registration_date    object
dtype: object

Employees
employee_id      int64
first_name      object
last_name       object
job_title       object
hire_date       object
salary         float64
email           object
dtype: object

Products
product_id          int64
product_name       object
category_id         int64
supplier_id         int64
unit_price        float64
units_in_stock      int64
reorder_level       int64
discontinued         bool
dtype: object

Categories
category_id       int64
category_name    object
description      object
dtype: object

Suppliers
supplier_id      int64
company_name    object
contact_name    object
phone           object
email           object
address         object
dtype: object

Inventory
inventory_id           int64
product_id             int64
quantity_available     int64
warehouse_location    object
last_updated          object
dtype: object

Orders
order_id         int64
customer_id      int64
employee_id      int64
order_date      object
order_status    object
dtype: object

Order Details
order_detail_id      int64
order_id             int64
product_id           int64
quantity             int64
unit_price         float64
discount           float64
dtype: object

Payments
payment_id          int64
order_id            int64
payment_date       object
payment_method     object
amount            float64
payment_status     object
dtype: object

In [ ]:
"""
Observation: The data-type assessment shows that most PrimeNest Retail columns have appropriate data types for analysis. Identifier and quantity fields 
are stored as integers (int64), while monetary fields such as salary, unit price, discount and payment amount are stored as floating-point values 
(float64). The discontinued field is correctly represented as a Boolean variable. Text-based fields are stored as objects, which is appropriate for 
names, addresses, categories and status fields.

However, the date fields — registration_date, hire_date, last_updated, order_date and payment_date — are currently stored as object rather than datetime 
values. These fields should therefore be converted to datetime format before conducting time-based analysis, such as monthly sales trends, payment 
trends or employee tenure analysis.

# - Check the Number of Unique Values

In [ ]:
#Looking for columns where the number of unique values may reveal something unusual.

In [20]:
for name, df in tables.items():
    print(f"\n{name}")
    print(df.nunique())

Customers
customer_id          20
first_name           20
last_name            20
gender                2
email                20
phone                20
address              20
city                 11
registration_date     1
dtype: int64

Employees
employee_id    10
first_name     10
last_name      10
job_title       9
hire_date      10
salary         10
email          10
dtype: int64

Products
product_id        20
product_name      20
category_id       10
supplier_id       10
unit_price        19
units_in_stock    14
reorder_level      5
discontinued       1
dtype: int64

Categories
category_id      10
category_name    10
description      10
dtype: int64

Suppliers
supplier_id     10
company_name    10
contact_name    10
phone           10
email           10
address         10
dtype: int64

Inventory
inventory_id          20
product_id            20
quantity_available    14
warehouse_location     3
last_updated           1
dtype: int64

Orders
order_id        100
customer_id      20
employee_id       9
order_date       85
order_status      5
dtype: int64

Order Details
order_detail_id    200
order_id           100
product_id          20
quantity             5
unit_price          19
discount           187
dtype: int64

Payments
payment_id        100
order_id          100
payment_date       85
payment_method      4
amount            100
payment_status      3
dtype: int64

In [ ]:
"""
Observation: The unique-value assessment shows good variation across most PrimeNest Retail fields, with IDs appropriately identifying individual records.
Categorical fields such as gender, order status, payment method and warehouse location provide useful variation for analysis. However, registration_date,
last_updated and discontinued each contain only one unique value, limiting their analytical usefulness.

Overall Data Quality Assessment — Observation

Observation: The PrimeNest Retail dataset is structurally complete, with no missing values or duplicate records across all nine tables. Most fields have appropriate data types and sufficient variation for analysis, while the date fields require conversion from object to datetime format before time-based analysis. A few fields, including registration date, inventory last-updated date and discontinued status, have limited variation and therefore offer limited analytical value.

# - Working on Fixing (Converting) the Date Fields

In [ ]:
#Convert Date Columns

In [ ]:
"""
From the assessment above, these five date columns are currently stored as object:

- customers['registration_date']
- employees['hire_date']
- inventory['last_updated']
- orders['order_date']
- payments['payment_date']

In [22]:
customers['registration_date'] = pd.to_datetime(customers['registration_date'])
employees['hire_date'] = pd.to_datetime(employees['hire_date'])
inventory['last_updated'] = pd.to_datetime(inventory['last_updated'])
orders['order_date'] = pd.to_datetime(orders['order_date'])
payments['payment_date'] = pd.to_datetime(payments['payment_date'])

In [23]:
print(customers['registration_date'].dtype)
print(employees['hire_date'].dtype)
print(inventory['last_updated'].dtype)
print(orders['order_date'].dtype)
print(payments['payment_date'].dtype)

datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]
datetime64[ns]

In [24]:
for name, df in tables.items():
    print(f"\n{name}")
    print(df.dtypes)

Customers
customer_id                   int64
first_name                   object
last_name                    object
gender                       object
email                        object
phone                        object
address                      object
city                         object
registration_date    datetime64[ns]
dtype: object

Employees
employee_id             int64
first_name             object
last_name              object
job_title              object
hire_date      datetime64[ns]
salary                float64
email                  object
dtype: object

Products
product_id          int64
product_name       object
category_id         int64
supplier_id         int64
unit_price        float64
units_in_stock      int64
reorder_level       int64
discontinued         bool
dtype: object

Categories
category_id       int64
category_name    object
description      object
dtype: object

Suppliers
supplier_id      int64
company_name    object
contact_name    object
phone           object
email           object
address         object
dtype: object

Inventory
inventory_id                   int64
product_id                     int64
quantity_available             int64
warehouse_location            object
last_updated          datetime64[ns]
dtype: object

Orders
order_id                 int64
customer_id              int64
employee_id              int64
order_date      datetime64[ns]
order_status            object
dtype: object

Order Details
order_detail_id      int64
order_id             int64
product_id           int64
quantity             int64
unit_price         float64
discount           float64
dtype: object

Payments
payment_id                 int64
order_id                   int64
payment_date      datetime64[ns]
payment_method            object
amount                   float64
payment_status            object
dtype: object

In [ ]:
"""
Observation: The data-type assessment confirms that the PrimeNest Retail dataset now has appropriate data types across its fields. Numeric, categorical 
and Boolean variables are correctly represented, while all date fields have been successfully converted from object to datetime64[ns]. The dataset is 
therefore properly formatted for subsequent analysis, calculations and time-based visualizations.

# EXPLORATORY DATA ANALYSYS (EDA)

In [ ]:
#Moving from “Is the data clean?” to “What is the data telling us about PrimeNest Retail?”

In [ ]:
"""
EDA Roadmap
1. Customer Analysis
2. Product & Category Analysis
3. Order & Sales Analysis
4. Revenue & Payment Analysis
5. Employee Performance Analysis
6. Inventory Analysis
7. Time-Based Analysis
8. Cross-table Business Analysis

In [ ]:
"""
Each section will have:

Question → Python/Pandas code → Output → Observation

# - Customer Analysis

In [ ]:
#How are PrimeNest Retail's customers distributed across cities?

In [25]:
customer_city = (
    customers['city']
    .value_counts()
    .reset_index()
)

customer_city.columns = ['city', 'customer_count']

customer_city

             city  customer_count
0           Lagos               4
1   Port Harcourt               3
2           Enugu               2
3           Abuja               2
4          Ibadan               2
5          Kaduna               2
6            Kano               1
7         Calabar               1
8          Owerri               1
9             Uyo               1
10     Benin City               1

In [ ]:
"""
- Customer Distribution by City: Observation

Customer distribution is concentrated mainly in Lagos (4 customers) and Port Harcourt (3 customers). Enugu, Abuja, Ibadan and Kaduna each have 2 
customers, while Kano, Calabar, Owerri, Uyo and Benin City each have 1 customer. This indicates that PrimeNest Retail has a geographically diverse 
customer base, although Lagos and Port Harcourt currently represent the strongest customer concentrations.

- Business Insight

PrimeNest Retail could prioritize marketing and customer engagement in Lagos and Port Harcourt, while exploring opportunities to increase customer 
acquisition in cities with lower representation.

# - Customer Gender Distribution

In [ ]:
#Shows the composition of the customer base

In [26]:
customer_gender = (
    customers['gender']
    .value_counts()
    .reset_index()
)

customer_gender.columns = ['gender', 'customer_count']

customer_gender

   gender  customer_count
0    Male              10
1  Female              10

In [ ]:
"""
- Customer Gender Distribution: Observation 
The customer base is evenly distributed by gender, with 10 male and 10 female customers. This represents a balanced 50/50 customer distribution, 
indicating that PrimeNest Retail's current customer base does not show a gender concentration.

- Business Insight

PrimeNest Retail can maintain gender-neutral marketing and customer engagement strategies, as the current customer base shows equal representation.

# - Order Status Distribution

In [ ]:
#Help to understand how PrimeNest Retail's orders are progressing through the sales process.

In [27]:
order_status = (
    orders['order_status']
    .value_counts()
    .reset_index()
)

order_status.columns = ['order_status', 'order_count']

order_status

  order_status  order_count
0    Delivered           28
1    Cancelled           25
2   Processing           21
3      Shipped           13
4      Pending           13

In [ ]:
"""
- Order Status Distribution: Observation

PrimeNest Retail recorded 28 delivered orders, making Delivered the most common order status. However, 25 orders were cancelled, representing a 
significant proportion of the 100 orders. A further 21 orders were processing, while 13 were shipped and 13 remained pending. The relatively high 
number of cancellations compared with successfully delivered orders indicates a potential area for operational review.

- Business Insight

The 25 cancelled orders deserve particular attention. PrimeNest Retail should investigate possible causes such as payment issues, stock availability, 
customer cancellations or delivery challenges to reduce order losses.

# - Product Analysis

In [ ]:
#Answers the question: Which products have the highest total quantity sold?

In [29]:
product_sales_named = (
    product_sales
    .merge(
        products[['product_id', 'product_name']],
        on='product_id',
        how='left'
    )
    [['product_id', 'product_name', 'quantity']]
)

product_sales_named

    product_id         product_name  quantity
0         1003       Wireless Mouse        39
1         1017       Protein Powder        38
2         1012     SQL Fundamentals        37
3         1016  Digital Thermometer        36
4         1002         HP Laptop 15        36
5         1015  Building Blocks Set        34
6         1008      Vitamin C Serum        32
7         1018             Rice 5kg        31
8         1007      Electric Kettle        31
9         1014   Remote Control Car        31
10        1001   Samsung Galaxy A55        30
11        1005      Women's Handbag        27
12        1013  Children Story Book        27
13        1004       Men's Sneakers        26
14        1011             Yoga Mat        25
15        1010             Football        25
16        1020         Office Chair        24
17        1019          Coffee 500g        23
18        1006              Blender        20
19        1009          Body Lotion        17

In [ ]:
"""
- Product Sales Volume: Observation

Sales volume varies considerably across the 20 products. Wireless Mouse recorded the highest quantity sold at 39 units, followed by Protein Powder (38) 
and SQL Fundamentals (37). At the lower end, Body Lotion recorded the lowest sales volume at 17 units, followed by Blender (20) and Coffee 500g (23). 
This indicates varying levels of customer demand across PrimeNest Retail's product range.

- Business Insight

PrimeNest Retail should prioritize high-demand products such as Wireless Mouse, Protein Powder and SQL Fundamentals for stock availability and 
promotional activities, while reviewing the pricing, positioning and demand for lower-performing products such as Body Lotion and Blender.

# - Sales by Product Category

In [ ]:
#This moves the analysis from individual products to the bigger picture(quantity): which categories are generating the most sales volume?

In [ ]:
"""
Because order_details has the quantity and products has the category_id, a merge of tables would be required. 

Then we connect the category information.

In [30]:
category_sales = (
    order_details
    .merge(
        products[['product_id', 'category_id']],
        on='product_id',
        how='left'
    )
    .merge(
        categories[['category_id', 'category_name']],
        on='category_id',
        how='left'
    )
    .groupby('category_name')['quantity']
    .sum()
    .reset_index()
    .sort_values('quantity', ascending=False)
)

category_sales

              category_name  quantity
2               Electronics       105
5                    Health        74
9            Toys and Games        65
1                     Books        64
4                 Groceries        54
3      Fashion and Clothing        53
6          Home and Kitchen        51
8       Sports and Outdoors        50
0  Beauty and Personal Care        49
7           Office Supplies        24

In [ ]:
"""
- Sales by Product Category: Observation
Electronics is the strongest-performing category, recording 105 units sold, followed by Health with 74 units and Toys and Games with 65 units. Office 
Supplies recorded the lowest sales volume at 24 units, while Beauty and Personal Care, Sports and Outdoors, and Home and Kitchen also recorded 
relatively lower volumes. This indicates that customer demand is particularly strong for Electronics and Health-related products.

- Business Insight

PrimeNest Retail should prioritize Electronics and Health products for inventory planning and marketing, while reviewing the performance of Office 
Supplies to identify opportunities to improve demand through pricing, promotion or product selection.

# - Revenue by Product

In [ ]:
#Moving from quantity sold to money generated.

In [ ]:
"""
Revenue will be calculated as:

Quantity × Unit Price − Discount

In [ ]:
#This will show which individual products generate the most revenue, which can be different from the products with the highest quantity sold.

In [31]:
product_revenue = (
    order_details.assign(
        revenue=lambda x: (x['quantity'] * x['unit_price']) - x['discount']
    )
    .groupby('product_id')['revenue']
    .sum()
    .reset_index()
    .merge(
        products[['product_id', 'product_name']],
        on='product_id',
        how='left'
    )
    [['product_id', 'product_name', 'revenue']]
    .sort_values('revenue', ascending=False)
)

product_revenue

    product_id         product_name      revenue
1         1002         HP Laptop 15  24479915.12
0         1001   Samsung Galaxy A55  12599947.66
19        1020         Office Chair   1631938.94
16        1017       Protein Powder   1215918.57
4         1005      Women's Handbag   1214916.97
3         1004       Men's Sneakers    909912.59
13        1014   Remote Control Car    774933.95
5         1006              Blender    759913.81
6         1007      Electric Kettle    681918.91
14        1015  Building Blocks Set    577912.81
17        1018             Rice 5kg    573411.03
7         1008      Vitamin C Serum    479912.00
2         1003       Wireless Mouse    467943.65
9         1010             Football    449909.38
11        1012     SQL Fundamentals    351429.28
10        1011             Yoga Mat    299926.69
15        1016  Digital Thermometer    251897.61
18        1019          Coffee 500g    172420.63
8         1009          Body Lotion    144412.78
12        1013  Children Story Book    134891.45

In [ ]:
"""
- Revenue by Product: Observation
Revenue is heavily concentrated in a few products. HP Laptop 15 generated the highest revenue at 24.48 million, followed by Samsung Galaxy A55 at 12.60 
million. Office Chair ranked third at approximately 1.63 million, while Children Story Book generated the lowest revenue at approximately 134,891. This 
shows that high-value products, particularly the two leading electronics products, contribute substantially more revenue than most other products.

- Business Insight

PrimeNest Retail should prioritize the availability of HP Laptop 15 and Samsung Galaxy A55, as disruptions in the supply of these products could have a 
significant impact on revenue. The business should also investigate opportunities to improve the performance of lower-revenue products.

- And there's an interesting point here: the products selling the most units aren't necessarily generating the most revenue. For example, Wireless Mouse 
sold the most units (39), but HP Laptop 15 generated by far the highest revenue. That's an important distinction we'll use later in the project.

# - Revenue by Category

In [ ]:
#Taking the same revenue calculation to the category level.

In [32]:
category_revenue = (
    order_details
    .assign(
        revenue=lambda x: (x['quantity'] * x['unit_price']) - x['discount']
    )
    .merge(
        products[['product_id', 'category_id']],
        on='product_id',
        how='left'
    )
    .merge(
        categories[['category_id', 'category_name']],
        on='category_id',
        how='left'
    )
    .groupby('category_name')['revenue']
    .sum()
    .reset_index()
    .sort_values('revenue', ascending=False)
)

category_revenue

              category_name      revenue
2               Electronics  37547806.43
3      Fashion and Clothing   2124829.56
7           Office Supplies   1631938.94
5                    Health   1467816.18
6          Home and Kitchen   1441832.72
9            Toys and Games   1352846.76
8       Sports and Outdoors    749836.07
4                 Groceries    745831.66
0  Beauty and Personal Care    624324.78
1                     Books    486320.73

In [ ]:
"""
- Revenue by Category: Observation

Revenue is heavily concentrated in Electronics, which generated approximately 37.55 million, far exceeding Fashion and Clothing at 2.12 million, the 
second-highest category. Books generated the lowest revenue at approximately 486,321. This indicates that Electronics is the primary revenue-driving 
category for PrimeNest Retail.

- Business Insight

PrimeNest Retail should prioritize Electronics inventory, pricing and marketing, as this category has a major influence on overall revenue. 
Lower-revenue categories should be reviewed to identify opportunities for improved pricing, promotion and product selection.

# - Monthly Order Volume & Revenue

"""
Question: How does PrimeNest Retail's order activity compare with the revenue generated each month?

- Inorder to compare orders and revenue, we'll group the Orders and Order Details data by month.

The calculation will thus, be:

- order_volume = number of unique orders in each month.

- revenue = quantity × unit price − discount, summed for each month.

(This is important because we're not just counting orders. We're looking at whether higher order activity is actually associated with higher revenue.

In [33]:
#Step 1: Create monthly order/revenue analysis

monthly_sales = (
    orders[['order_id', 'order_date']]
    .merge(
        order_details[['order_id', 'quantity', 'unit_price', 'discount']],
        on='order_id',
        how='left'
    )
    .assign(
        revenue=lambda x: (x['quantity'] * x['unit_price']) - x['discount'],
        month=lambda x: x['order_date'].dt.to_period('M').astype(str)
    )
    .groupby('month')
    .agg(
        order_volume=('order_id', 'nunique'),
        revenue=('revenue', 'sum')
    )
    .reset_index()
    .sort_values('month')
)

monthly_sales

      month  order_volume      revenue
0   2025-01             9   3186379.07
1   2025-02             9   6359369.28
2   2025-03             8   3172928.96
3   2025-04            10   1474313.23
4   2025-05             6   1883436.94
5   2025-06            14  10276734.65
6   2025-07            11   4545333.08
7   2025-08             5   1832949.47
8   2025-09            10   4771750.64
9   2025-10             8   1041850.19
10  2025-11             7   9295884.55
11  2025-12             3    332453.77

In [ ]:
"""
- Monthly Order Volume & Revenue: Observation

Monthly order activity and revenue show considerable variation throughout 2025. June recorded the highest order volume with 14 orders and generated 
approximately 10.28 million in revenue. November generated the second-highest revenue at approximately 9.30 million despite having only 7 orders, 
indicating that revenue is influenced not only by order volume but also by the value of products purchased. December recorded the lowest order volume 
(3) and revenue (approximately 332,454).

- Business Insight

The results show that higher order volume does not always translate into higher revenue. PrimeNest Retail should therefore monitor both order frequency 
and order value when evaluating monthly sales performance.

# - Payment Method Analysis

In [ ]:
#This answers: Which payment methods are most commonly used by PrimeNest Retail customers?

In [34]:
payment_methods = (
    payments['payment_method']
    .value_counts()
    .reset_index()
)

payment_methods.columns = ['payment_method', 'payment_count']

payment_methods

     payment_method  payment_count
0  Cash on Delivery             37
1            PayPal             27
2     Bank Transfer             21
3              Card             15

In [ ]:
"""
- Payment Method Analysis: Observation
Cash on Delivery is the most commonly used payment method, accounting for 37 payments, followed by PayPal with 27 and Bank Transfer with 21. Card 
payments were the least common, with 15 transactions. This indicates a strong preference for Cash on Delivery among PrimeNest Retail customers.

- Business Insight

PrimeNest Retail should continue supporting Cash on Delivery while maintaining digital options such as PayPal and Bank Transfer. The relatively low use 
of card payments may also present an opportunity to investigate customer preferences or barriers to card-based payments.

# - Employee Sales Performance

In [ ]:
#Answers: Which employees handle the highest number of orders and generate the most revenue?

In [35]:
employee_sales = (
    orders[['order_id', 'employee_id']]
    .merge(
        order_details[['order_id', 'quantity', 'unit_price', 'discount']],
        on='order_id',
        how='left'
    )
    .assign(
        revenue=lambda x: (x['quantity'] * x['unit_price']) - x['discount']
    )
    .groupby('employee_id')
    .agg(
        order_count=('order_id', 'nunique'),
        revenue=('revenue', 'sum')
    )
    .reset_index()
    .sort_values('revenue', ascending=False)
    .merge(
        employees[['employee_id', 'first_name', 'last_name']],
        on='employee_id',
        how='left'
    )
)

employee_sales

   employee_id  order_count      revenue first_name last_name
0       101284           16  16238204.15     Olivia     Jones
1       101282           12   5862296.76     Sophia  Williams
2       101289            9   5548897.24      Henry    Thomas
3       101287           19   5400732.11   Benjamin    Taylor
4       101285           11   4862781.67      James    Garcia
5       101288           12   4860287.35  Charlotte  Anderson
6       101283            9   4292852.89     Daniel     Brown
7       101281            5    663419.42    Michael   Johnson
8       101286            7    443912.24       Emma  Martinez

In [ ]:
"""
- Employee Sales Performance: Observation

Employee performance varies considerably across the 9 employees. Olivia Jones generated the highest revenue at approximately 16.24 million from 16 
orders, despite not handling the highest number of orders. Benjamin Taylor handled the most orders (19) but generated approximately 5.40 million in 
revenue. Michael Johnson recorded the lowest revenue at approximately 663,419 from 5 orders.

This shows that order volume does not necessarily translate into higher revenue. Olivia's performance suggests that the value of the orders she handles 
is substantially higher.

- Business Insight

PrimeNest Retail should examine the sales approach and customer/order mix associated with high-performing employees, particularly Olivia Jones, and 
identify practices that could potentially be replicated across the wider sales team.

# - Customer Spending Analysis

In [ ]:
#Question is: Which customers generate the most revenue for PrimeNest Retail?

In [ ]:
#To answer the above question, orders, order_details, and customers will be combined to calculate each customer's total spending.

In [37]:
customer_spending = (
    orders[['order_id', 'customer_id']]
    .merge(
        order_details[['order_id', 'quantity', 'unit_price', 'discount']],
        on='order_id',
        how='left'
    )
    .assign(
        spending=lambda x: (x['quantity'] * x['unit_price']) - x['discount']
    )
    .groupby('customer_id')
    .agg(
        order_count=('order_id', 'nunique'),
        total_spending=('spending', 'sum')
    )
    .reset_index()
    .merge(
        customers[['customer_id', 'first_name', 'last_name']],
        on='customer_id',
        how='left'
    )
    .sort_values('total_spending', ascending=False)
)

customer_spending

    customer_id  order_count  total_spending first_name last_name
4          1105            9      6623336.81      Tunde   Adebayo
11         1112            7      5591400.53      Mercy   Ibrahim
17         1118            6      5466871.39        Joy    Nnamdi
8          1109            7      4745359.26     Samuel       Ojo
15         1116            4      4710436.72      Faith      Okon
1          1102            8      3710350.58        Ada       Eze
3          1104            3      3619458.56      Ngozi      Umeh
6          1107            8      2796366.24    Ifeanyi       Obi
10         1111            5      2522911.95     Daniel     Okeke
18         1119            8      2206893.93     Kelvin    George
14         1115            5      2162950.63     Victor   Adewale
13         1114            6      1787404.18       Ruth   Ogbonna
7          1108            5       652427.31   Blessing     James
9          1110            3       431438.20     Esther   Daniels
5          1106            2       291458.92      Aisha     Bello
2          1103            2       262451.77      Emeka     Nwosu
12         1113            4       209954.25       Paul    Ekanem
16         1117            4       183465.22      Henry     Usman
19         1120            1       102980.76     Chioma    Onyeka
0          1101            3        95466.62    Chinedu    Okafor

In [ ]:
"""
- Customer Spending: Observation

Customer spending varies significantly across PrimeNest Retail's customer base. Tunde Adebayo is the highest-value customer, generating approximately 
6.62 million from 9 orders, followed by Mercy Ibrahim (5.59 million) and Joy Nnamdi (5.47 million). At the lower end, Chinedu Okafor generated 
approximately 95,467 from 3 orders. The results show that a relatively small group of customers contributes substantially more revenue than others.

- Business Insight

PrimeNest Retail should prioritize customer retention and personalized engagement for high-value customers, while exploring strategies such as targeted 
promotions and product recommendations to increase spending among lower-value customers.

# - Inventory Analysis

In [ ]:
"""
It will answer the qestion: 

    Which products have the lowest available inventory, and how does their stock compare with their reorder levels?

In [38]:
inventory_analysis = (
    inventory[['product_id', 'quantity_available']]
    .merge(
        products[['product_id', 'product_name', 'reorder_level']],
        on='product_id',
        how='left'
    )
    .assign(
        stock_buffer=lambda x: x['quantity_available'] - x['reorder_level']
    )
    .sort_values('stock_buffer')
)

inventory_analysis

,product_id,quantity_available,product_name,reorder_level,stock_buffer
19,1020,25,Office Chair,5,20
1,1002,30,HP Laptop 15,5,25
16,1017,30,Protein Powder,5,25
13,1014,35,Remote Control Car,5,30
11,1012,40,SQL Fundamentals,10,30
5,1006,40,Blender,8,32
14,1015,45,Building Blocks Set,8,37
0,1001,50,Samsung Galaxy A55,10,40
9,1010,50,Football,10,40
10,1011,65,Yoga Mat,15,50
4,1005,60,Women's Handbag,10,50
17,1018,60,Rice 5kg,10,50
6,1007,70,Electric Kettle,15,55
12,1013,80,Children Story Book,15,65
3,1004,80,Men's Sneakers,15,65
8,1009,90,Body Lotion,20,70
18,1019,90,Coffee 500g,20,70
7,1008,100,Vitamin C Serum,20,80
15,1016,110,Digital Thermometer,20,90
2,1003,120,Wireless Mouse,20,100

In [ ]:
"""
- Inventory Analysis: Observation

Inventory levels are generally above their respective reorder levels, with all products maintaining a positive stock buffer. Office Chair has the lowest 
stock buffer at 20 units, followed by HP Laptop 15 and Protein Powder at 25 units each. Wireless Mouse has the highest available stock at 120 units and 
the largest stock buffer of 100 units. No product currently falls below its reorder level.

- Business Insight

Although no immediate reorder requirement exists, Office Chair should receive the closest inventory monitoring because it has the smallest stock buffer. 
High-demand products such as HP Laptop 15 and Protein Powder should also be monitored closely to prevent future stock shortages.

Exploratory Data Analysis: Conclusion

Conclusion: The exploratory analysis of PrimeNest Retail revealed important patterns across customers, products, sales, revenue, employees, payments and inventory. Customer distribution is relatively diverse, with stronger concentrations in Lagos and Port Harcourt and an even gender split. Electronics emerged as the strongest-performing category, generating approximately 37.55 million in revenue, with the HP Laptop 15 and Samsung Galaxy A55 contributing significantly to overall revenue.

Sales activity varied considerably throughout the year, and the monthly analysis demonstrated that higher order volumes do not necessarily result in higher revenue. Employee and customer analyses also revealed significant differences in revenue contribution, with Olivia Jones and Tunde Adebayo emerging as the highest-performing employee and customer respectively. Cash on Delivery was the most commonly used payment method.

Inventory levels were generally healthy, with all products maintaining stock above their reorder levels. However, Office Chair had the smallest stock buffer and therefore warrants closer monitoring. Overall, the analysis provides PrimeNest Retail with useful insights for inventory planning, customer retention, sales management, product prioritization and revenue growth.